name: 3D Contribution
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          username: jask1123
          output_dir: ./profile-3d-contrib
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./profile-3d-contrib
          git commit -m "Generate 3D Contribution"
          git push 
